// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    var colors, i, j;
    colors = ["red", "green", "blue", "pink", "yellow", "orange"];
    for (i = j = 0; j < 600; i = ++j) {
      $("#box").prepend("<div class='point'></div>");
    }
    return $("#box .point").each(function(index) {
      return $(this).css({
        background: colors[Math.floor(Math.random() * (colors.length - 0 + 1)) + 0]
      }).animate({
        marginLeft: (150 * (index / 600)) * Math.sin(index / 10) + 700
      }, 3000);
    });
  });

}).call(this);

//# sourceMappingURL=script.js.map
