// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    $(".menuitem").mouseover(function() {
      var $this;
      $this = $(this);
      return $("#menuItem-hover").addClass("visible").css({
        left: ($this.offset().left + $this.innerWidth() / 2) - $("#menuItem-hover").width() / 2
      });
    }).mouseout(function() {
      return $("#menuItem-hover").removeClass("visible");
    });
    $(document).scroll(function() {
      if ($(this).scrollTop() > $("#header").height() / 3) {
        return $("#mainMenu").addClass("scroll");
      } else {
        return $("#mainMenu").removeClass("scroll");
      }
    });
    return $(".square").each(function() {
      var $this;
      $this = $(this);
      $this.css({
        width: $this.height()
      });
      return $(window).resize(function() {
        return $this.css({
          width: $this.height()
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=script.js.map
