// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    var getWindowSize, lg, md, sm, xl;
    getWindowSize = function() {
      if ($(window).width() < 768) {
        return xl();
      }
      if ($(window).width() < 992) {
        return sm();
      }
      if ($(window).width() < 1120) {
        return md();
      } else {
        return lg();
      }
    };
    xl = function() {
      return $("body").addClass("container-fluid");
    };
    sm = function() {
      return $("body").removeClass("container-fluid");
    };
    md = function() {
      return $("body").removeClass("container-fluid");
    };
    lg = function() {
      return $("body").removeClass("container-fluid");
    };
    getWindowSize();
    $(window).resize(function() {
      return getWindowSize();
    });
    $("*.card").each(function() {
      var $this, attr, source;
      $this = this;
      attr = function(attr) {
        return $("." + attr, $this).text().split(" | ");
      };
      source = "<div class='title'></div><div class='text'></div>";
      $(this).prepend(source);
      $(this).css({
        backgroundImage: "url( " + (attr("imagem")) + " )"
      });
      $(".title", this).prepend(attr("titulo")[0]).css({
        color: attr("titulo")[1]
      });
      $(".text", this).prepend(attr("texto")[0]).css({
        background: attr("texto")[1],
        color: attr("texto")[2],
        marginTop: $($this).width() - ($(".text", $this).innerHeight() + $(".title", $this).innerHeight()) + "px"
      });
      return $(".imagem,.titulo,.texto", this).remove();
    });
    return $("*[animated]").each(function(index, callback) {
      var $this;
      $this = $(this);
      return $.each(callback.attributes, function(index, callback) {
        var $val;
        $val = callback.value.split(" ");
        if (callback.name === "animated") {
          return $this.addClass("animated").addClass($val[0]).css("animation-delay", $val[1] + "s").css("animation-duration", $val[2] + "s");
        }
      });
    });
  });


  /*  $(".card").on "click", ->
      $this = $( this )
      $this
        .css {
          position: "fixed"
          left: "calc( 50% - " + $this.width() / 2 + "px )"
          top: "calc( 50% - " + $this.height() / 2 + "px )"
        }
   */

}).call(this);

//# sourceMappingURL=script.js.map
