// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    var getWindowSize, lg, md, sm, xl;
    getWindowSize = function() {
      if ($(window).width() < 768) {
        return xl();
      }
      if ($(window).width() < 992) {
        return sm();
      }
      if ($(window).width() < 1120) {
        return md();
      } else {
        return lg();
      }
    };
    xl = function() {
      return $("body").addClass("container-fluid");
    };
    sm = function() {
      return $("body").removeClass("container-fluid");
    };
    md = function() {
      return $("body").removeClass("container-fluid");
    };
    lg = function() {
      return $("body").removeClass("container-fluid");
    };
    getWindowSize();
    $(window).resize(function() {
      return getWindowSize();
    });
    $("*[animated]").each(function(index, callback) {
      var $this;
      $this = $(this);
      return $.each(callback.attributes, function(index, callback) {
        var $val;
        $val = callback.value.split(" ");
        if (callback.name === "animated") {
          return $this.addClass("animated").addClass($val[0]).css("animation-delay", $val[1] + "s").css("animation-duration", $val[2] + "s");
        }
      });
    });
    $("#slideBox #indexes div").on("click", function() {
      var $attr, $this;
      $this = $(this);
      $attr = function(attr) {
        return $this.children("." + attr).text();
      };
      $("#header").css({
        backgroundImage: "url(" + $attr("image") + ")"
      });
      $("#slideBox #text").fadeOut(function() {
        $(this).children().empty();
        $(this).children("h1").prepend($attr("title"));
        return $(this).children("h4").prepend($attr("text"));
      }).delay(10).fadeIn();
      $("#slideBox #indexes div").removeClass("selected");
      return $this.addClass("selected");
    });
    return $("#slideBox #indexes div:first").trigger("click");
  });

}).call(this);

//# sourceMappingURL=script.js.map
